// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace weRid {
	
	
	public partial class MyPage {
		
		protected System.Web.UI.HtmlControls.HtmlForm form;

		protected System.Web.UI.WebControls.Panel Paneltopmenu;

		protected System.Web.UI.WebControls.ImageButton poisk;

		protected System.Web.UI.WebControls.ImageButton avatar;

		protected System.Web.UI.WebControls.TextBox TextBoxPoisk;

		protected System.Web.UI.WebControls.LinkButton name;

		protected System.Web.UI.WebControls.ImageButton logo1;

		protected System.Web.UI.WebControls.ImageButton exit;

		protected System.Web.UI.WebControls.Panel topPanelbutton;

		protected System.Web.UI.WebControls.Button tekuchie;

		protected System.Web.UI.WebControls.Button popula;

		protected System.Web.UI.WebControls.Panel Panelmenu;

		protected System.Web.UI.WebControls.Button glbutton;

		protected System.Web.UI.WebControls.Button mypage;

		protected System.Web.UI.WebControls.Button takebutton;

		protected System.Web.UI.WebControls.Button givebutton;

		protected System.Web.UI.WebControls.TextBox TextBoxPoisk1;

		protected System.Web.UI.WebControls.Panel MainPanel;

		protected System.Web.UI.WebControls.Table Table1;

		protected System.Web.UI.WebControls.Label hiden;

		protected System.Web.UI.WebControls.Panel botPanelbutton;

		protected System.Web.UI.WebControls.ImageButton logo123;

		protected System.Web.UI.WebControls.ImageButton info;

		protected System.Web.UI.UpdatePanel UpdatePanel1;

		protected System.Web.UI.WebControls.Login Login1;

		protected System.Web.UI.WebControls.ImageButton Foto;

		protected System.Web.UI.WebControls.Panel infoPolzovat;

		protected System.Web.UI.WebControls.Label name1;

		protected System.Web.UI.WebControls.Label karma;

		protected System.Web.UI.WebControls.Panel infoLichnaya;

		protected System.Web.UI.WebControls.Label date;

		protected System.Web.UI.WebControls.Label countri;

		protected System.Web.UI.WebControls.Label toun;

		protected System.Web.UI.WebControls.Label work;

		protected System.Web.UI.WebControls.Label podpisan;

		protected System.Web.UI.WebControls.Label podpischiki;

		protected System.Web.UI.WebControls.Label posts;

	}
}
