// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace weRid {
	
	
	public partial class Default {
		
protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox sdf;
		
		protected System.Web.UI.WebControls.Panel panelfon1;
		
		protected System.Web.UI.WebControls.Button Registration;
		
		protected System.Web.UI.WebControls.Button Auterification;
		
		protected System.Web.UI.WebControls.Panel panelfon;
		
		protected System.Web.UI.WebControls.Label LableZaglav;
		
		protected System.Web.UI.WebControls.Label LableLogin;
		
		protected System.Web.UI.WebControls.TextBox TextLogin;
		
		protected System.Web.UI.WebControls.Label LablePasswd;
		
		protected System.Web.UI.WebControls.TextBox TextPasswd;
		
		protected System.Web.UI.WebControls.Button Auterification2;
		
		protected System.Web.UI.WebControls.Panel panelfon2;
		
		protected System.Web.UI.WebControls.Label TextReg;
		
		protected System.Web.UI.WebControls.Label name2;
		
		protected System.Web.UI.WebControls.TextBox nameText;
		
		protected System.Web.UI.WebControls.Label login2;
		
		protected System.Web.UI.WebControls.TextBox loginText;
		
		protected System.Web.UI.WebControls.Label Passwd;
		
		protected System.Web.UI.WebControls.TextBox PasswdText;
		
		protected System.Web.UI.WebControls.Label Passwd2;
		
		protected System.Web.UI.WebControls.TextBox PasswdText2;
		
		protected System.Web.UI.WebControls.Label pol;
		
		protected System.Web.UI.WebControls.DropDownList polText;
		
		protected System.Web.UI.WebControls.Label NumTel;
		
		protected System.Web.UI.WebControls.TextBox NumTelText;
		
		protected System.Web.UI.WebControls.Label Prov;
		
		protected System.Web.UI.WebControls.ImageButton Prov2;
		
		protected System.Web.UI.WebControls.TextBox ProvText;
		
		protected System.Web.UI.WebControls.Button Registration2;
		

	}
}
